### PR TITLE
No whitespace on the sides of the canvas

### PR DESCRIPTION
**Pull request by Codezigineer**

### CODE REVIEW

**Comment by Beakerboy** [comment]
Wow! First pull request from someone who is not me!
Can you please tell me what looks wrong with the output the way it is? What problem does this pull request fix?

**Comment by Codezigineer** [comment]
It shows the body element on the left side of the page. screenshot

**Comment by Beakerboy** [comment]
Why is this a problem? What should it look like? I loaded the Jefferson Monument example, changed the CSS in the browser developer tools and nothing changed.

**Comment by Beakerboy** [comment]
Never mind. It shifted slightly.

looks good

**Comment by Codezigineer** [comment]
Oh.

**Comment by Beakerboy** [comment]
Let me know of there is anything else you see. I’m open to any pull requests and collaboration.

**Pull request merged**
